site_name: Profiling GPU Apps with NSight-Systems on MeluXina 
site_description: Webinar/Tutorial on how to Profile GPU Apps with NSight-Systems on MeluXina
site_url: "https://LuxProvide.github.io/GPU-Profiling-NSight-Systems-MeluXina/"

site_author: Marco Magliulo, Emmanuel Kieffer, Xavier Besseron
site_dir: public

nav:
    - 🏠 Overview: index.md
    - 1️⃣ Settings things up: setup.md
    - 2️⃣ Getting Started With NSight Systems: nsight_systems.md
    - 3️⃣ Optimize a slow PyTorch distributed training: optimizing.md

exclude_docs: |
    *.backup

# strict: true
validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn

theme:
    #include_homepage_in_sidebar: False
    #navigation_depth: 4
    #collapse_navigation: True
    #titles_only: False
    #sticky_navigation: True
    name: material
    logo: assets/LuxProvide_logo_white.svg
    favicon: assets/favicon.png
    language: en
    features:
        - navigation.expand
        - navigation.footer
        - navigation.sections
        - navigation.path
        - toc.integrate
        - content.code.copy
        - content.code.select
        - content.code.annotate
        #- navigation.tabs

plugins:
    - search
    - progress
    - include-markdown
    - open-in-new-tab

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - md_in_html
    - tables
    - admonition
    - toc:
          permalink: true
    - codehilite:
          guess_lang: true
    - footnotes
    - markdown_include.include:
          base_path: docs
    - markdown.extensions.admonition
    - meta
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.magiclink:
          repo_url_shorthand: true
          social_url_shorthand: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
